version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jpsc_app
    working_dir: /var/www/html
    volumes:
      - ./src/myapp:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: jpsc_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jpsc
      MYSQL_USER: jpsc
      MYSQL_PASSWORD: Test@1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
